from building import *
import os

cwd = GetCurrentDir()
project_root = os.path.abspath(os.path.join(cwd, '..', '..'))
usb_root = os.path.join(
    project_root, 'libraries', 'components', 'emusb-device'
)
usb_paths = [
    os.path.join(cwd, 'include'),
    os.path.join(usb_root, 'USBD'),
    os.path.join(usb_root, 'USBD', 'COMPONENT_PSE84'),
]
usb_depend = ['BSP_USING_USB']
usb_only = os.environ.get('HBALL_USB_ONLY', '0') == '1'
integrated_shadow = os.environ.get('HBALL_INTEGRATED_SHADOW', '0') == '1'
mission_protocol_root = os.environ.get(
    'HBALL_MISSION_PROTOCOL_ROOT',
    os.path.join(project_root, 'shared', 'protocol'),
)

if usb_only:
    usb_only_src = [
        os.path.join(cwd, 'rtthread', 'main.c'),
        os.path.join(cwd, 'src', 'hball_usb_probe.c'),
        os.path.join(cwd, 'src', 'hball_rate_meter.c'),
        os.path.join(cwd, 'src', 'hball_log_protocol.c'),
        os.path.join(cwd, 'src', 'hball_vision_protocol.c'),
        os.path.join(cwd, 'rtthread', 'hball_usb_cdc.c'),
    ]
    group = DefineGroup(
        'HBallEdgeTalkUsbOnly',
        usb_only_src,
        depend=usb_depend,
        CPPPATH=usb_paths,
        CPPDEFINES=['HBALL_USB_ONLY=1'],
    )
elif integrated_shadow:
    integrated_src = [
        os.path.join(cwd, 'src', 'hball_can.c'),
        os.path.join(cwd, 'src', 'hball_control_guard.c'),
        os.path.join(cwd, 'src', 'hball_control_pipeline.c'),
        os.path.join(cwd, 'src', 'hball_deployment_controller.c'),
        os.path.join(cwd, 'src', 'hball_dualcore_ipc.c'),
        os.path.join(cwd, 'src', 'hball_dualcore_platform.c'),
        os.path.join(cwd, 'src', 'hball_fourbar.c'),
        os.path.join(cwd, 'src', 'hball_lqg.c'),
        os.path.join(cwd, 'src', 'hball_rate_meter.c'),
        os.path.join(cwd, 'src', 'hball_log_protocol.c'),
        os.path.join(cwd, 'src', 'hball_mission_arbiter.c'),
        os.path.join(cwd, 'src', 'hball_rs00_control.c'),
        os.path.join(cwd, 'src', 'hball_sensor_fusion.c'),
        os.path.join(cwd, 'src', 'hball_usb_probe.c'),
        os.path.join(cwd, 'src', 'hball_vision_protocol.c'),
        os.path.join(cwd, 'rtthread', 'hball_bench_app.c'),
        os.path.join(cwd, 'rtthread', 'hball_m33_control_guard.c'),
        os.path.join(cwd, 'rtthread', 'hball_m33_inputs.c'),
        os.path.join(cwd, 'rtthread', 'hball_usb_cdc.c'),
        os.path.join(cwd, 'rtthread', 'main.c'),
        os.path.join(mission_protocol_root, 'hball_mission_can.c'),
    ]
    group = DefineGroup(
        'HBallEdgeTalkIntegratedShadow',
        integrated_src,
        depend=usb_depend,
        CPPPATH=usb_paths + [
            os.path.join(project_root, 'libraries', 'HAL_Drivers'),
            mission_protocol_root,
        ],
        CPPDEFINES=[
            'HBALL_INTEGRATED_SHADOW=1',
            'HBALL_BENCH_AUTO_PROBE5=0',
            'HBALL_RS00_READBACK_TX_ENABLED=1',
            'HBALL_RS00_MOTION_TX_ENABLED=1',
            'BSP_CANFD0_RX_FIFO0_ELEMENTS=64U',
        ],
    )
else:
    base_src = [
        os.path.join(cwd, 'src', 'hball_can.c'),
        os.path.join(cwd, 'src', 'hball_mission_arbiter.c'),
        os.path.join(cwd, 'src', 'hball_rate_meter.c'),
        os.path.join(cwd, 'rtthread', 'hball_bench_app.c'),
        os.path.join(cwd, 'rtthread', 'main.c'),
        os.path.join(mission_protocol_root, 'hball_mission_can.c'),
    ]
    cppdefines = ['BSP_CANFD0_RX_FIFO0_ELEMENTS=64U']
    if os.environ.get('HBALL_BENCH_AUTO_PROBE5', '0') == '1':
        cppdefines.append('HBALL_BENCH_AUTO_PROBE5=1')

    group = DefineGroup(
        'HBallEdgeTalkBench',
        base_src,
        depend=[''],
        CPPPATH=[
            os.path.join(cwd, 'include'),
            os.path.join(project_root, 'libraries', 'HAL_Drivers'),
            mission_protocol_root,
        ],
        CPPDEFINES=cppdefines,
    )
    usb_src = [
        os.path.join(cwd, 'src', 'hball_usb_probe.c'),
        os.path.join(cwd, 'src', 'hball_log_protocol.c'),
        os.path.join(cwd, 'src', 'hball_vision_protocol.c'),
        os.path.join(cwd, 'rtthread', 'hball_usb_cdc.c'),
    ]
    usb_group = DefineGroup(
        'HBallEdgeTalkUsbProbe',
        usb_src,
        depend=usb_depend,
        CPPPATH=usb_paths,
    )
    group = group + usb_group
Return('group')
