/* H-ball EdgeTalk M33 USB Device CDC probe fragment. */
#define RT_USING_CHERRYUSB
#define RT_CHERRYUSB_DEVICE
#define RT_CHERRYUSB_DEVICE_SPEED_FS
#define RT_CHERRYUSB_DEVICE_DWC2_INFINEON
#define RT_CHERRYUSB_DEVICE_CDC_ACM
#define RT_CHERRYUSB_DEVICE_CDC_ACM_CHARDEV
#define RT_CHERRYUSB_DEVICE_TEMPLATE_NONE
